name: untitled
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  firebase_database: ^12.0.0
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  google_sign_in: ^7.1.1
  location: ^8.0.1
  google_maps_flutter: ^2.12.3
  geolocator: ^14.0.2
  cupertino_icons: ^1.0.8
  firebase_messaging: ^16.0.0
  flutter_local_notifications: ^19.4.0
  url_launcher: ^6.3.0
  google_mlkit_text_recognition: ^0.15.0
  http: ^1.5.0
  flutter_polyline_points: ^3.0.1
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/bus1.png
    - assets/images/bus2.png
    - assets/images/bus3.png
